server:
  port: 8085
  url: "http://localhost:${server.port}"
  version: "1.0"


spring:
  application:
    name: profile
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/one_bank_profile
    username: postgres
    password: siroj1294
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "profile"
    description: "Microservice profile application"
    version: "1.0.0"