server:
  port: 8083
  url: "http://localhost:${server.port}"
  version: "1.0"


spring:
  application:
    name: notification
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/one_bank_notification
    username: postgres
    password: siroj1294
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

