spring:
  application:
  name: "eureka-server"
  profiles:
    active: "dev"
server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
